project_id = "zcempgdbwezipccexcyt"

[functions.import-disciplines]
verify_jwt = false

[functions.generate-syllabus]
verify_jwt = false

[functions.fetch-step-resources]
verify_jwt = false

[functions.generate-step-summary]
verify_jwt = false

[functions.report-replace-resource]
verify_jwt = false

[functions.generate-assignment]
verify_jwt = false

[functions.find-additional-resource]
verify_jwt = false

[functions.recover-podcast-link]
verify_jwt = false

[functions.generate-discipline-image]
verify_jwt = false

[functions.ai-match-discipline]
verify_jwt = false

[functions.translate-disciplines]
verify_jwt = false

[functions.infer-topic-pillars]
verify_jwt = false

[functions.generate-schedule]
verify_jwt = false

[functions.recalibrate-schedule]
verify_jwt = false
