project_id = "zcempgdbwezipccexcyt"

[functions.import-disciplines]
verify_jwt = false

[functions.generate-syllabus]
verify_jwt = false

[functions.fetch-step-resources]
verify_jwt = false

[functions.generate-step-summary]
verify_jwt = false

[functions.report-replace-resource]
verify_jwt = false

[functions.generate-assignment]
verify_jwt = false
